### ISSUE TITLE
Failure in installing SCS in MATLAB on macOS

### ISSUE THREAD

**Issue by hayata-yamasaki** [cvxgrp/scs#106]
I report an installation problem of scs-matlab on macOS Mojave 10.14.4, while I am not sure from which of SCS or scs-matlab this problem arises.

I downloaded SCS by
```
git clone --recursive https://github.com/bodono/scs-matlab.git  
```

Then, on MATLAB_R2018b, I obtained the following failure in performing tests of SCS.
```
>> make_scs
Building with 'Xcode with Clang'.
MEX completed successfully.
Building with 'Xcode with Clang'.
MEX completed successfully.
Building with 'Xcode with Clang'.
MEX completed successfully.
Example run:
----------------------------------------------------------------------------
	SCS v2.0.2 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012-2017
----------------------------------------------------------------------------
Lin-sys: sparse-indirect, nnz in A = 27, CG tol ~ 1/iter^(2.00)
eps = 1.00e-05, alpha = 1.50, max_iters = 5000, normalize = 1, scale = 1.00
acceleration_lookback = 20, rho_x = 1.00e-03
Variables n = 3, constraints m = 9
Cones:	linear vars: 9
Setup time: 1.01e-02s
----------------------------------------------------------------------------
 Iter | pri res | dua res | rel gap | pri obj | dua obj | kap/tau | time (s)
----------------------------------------------------------------------------
Failure:Interrupted
----------------------------------------------------------------------------
	SCS v2.0.2 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012-2017
----------------------------------------------------------------------------
Lin-sys: sparse-direct, nnz in A = 27
eps = 1.00e-05, alpha = 1.50, max_iters = 5000, normalize = 1, scale = 1.00
acceleration_lookback = 20, rho_x = 1.00e-03
Variables n = 3, constraints m = 9
Cones:	linear vars: 9
interrupt detected in factorization
ERROR: init_lin_sys_work failure
Setup time: 4.45e-02s
Failure:could not initialize work
Warm-starting:
----------------------------------------------------------------------------
	SCS v2.0.2 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012-2017
----------------------------------------------------------------------------
Lin-sys: sparse-indirect, nnz in A = 27, CG tol ~ 1/iter^(2.00)
eps = 1.00e-05, alpha = 1.50, max_iters = 5000, normalize = 1, scale = 1.00
acceleration_lookback = 20, rho_x = 1.00e-03
Variables n = 3, constraints m = 9
Cones:	linear vars: 9
Setup time: 5.63e-02s
SCS using variable warm-starting
----------------------------------------------------------------------------
 Iter | pri res | dua res | rel gap | pri obj | dua obj | kap/tau | time (s)
----------------------------------------------------------------------------
Failure:Interrupted
SUCCESSFULLY INSTALLED SCS
(If using SCS with CVX, note that SCS only supports CVX v3.0 or later).
```

**Comment by bodono** [comment]
Should be fixed now.

**Comment by hayata-yamasaki** [comment]
I appreciate your quick response.

**Comment by hayata-yamasaki** [comment]
I appreciate your quick response.
However, using the same commands as the above, I still get the following failure.
```
>> make_scs
Building with 'Xcode with Clang'.
MEX completed successfully.
Building with 'Xcode with Clang'.
MEX completed successfully.
Building with 'Xcode with Clang'.
MEX completed successfully.
Example run:
----------------------------------------------------------------------------
	SCS v2.1.0 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
----------------------------------------------------------------------------
Lin-sys: sparse-indirect, nnz in A = 27, CG tol ~ 1/iter^(2.00)
eps = 1.00e-05, alpha = 1.50, max_iters = 5000, normalize = 1, scale = 1.00
acceleration_lookback = 10, rho_x = 1.00e-03
Variables n = 3, constraints m = 9
Cones:	linear vars: 9
Setup time: 1.35e-02s
----------------------------------------------------------------------------
 Iter | pri res | dua res | rel gap | pri obj | dua obj | kap/tau | time (s)
----------------------------------------------------------------------------
Failure:Interrupted
----------------------------------------------------------------------------
	SCS v2.1.0 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
----------------------------------------------------------------------------
Lin-sys: sparse-direct, nnz in A = 27
eps = 1.00e-05, alpha = 1.50, max_iters = 5000, normalize = 1, scale = 1.00
acceleration_lookback = 10, rho_x = 1.00e-03
Variables n = 3, constraints m = 9
Cones:	linear vars: 9
interrupt detected in factorization
ERROR: init_lin_sys_work failure
Setup time: 7.89e-03s
Failure:could not initialize work
Warm-starting:
----------------------------------------------------------------------------
	SCS v2.1.0 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
----------------------------------------------------------------------------
Lin-sys: sparse-indirect, nnz in A = 27, CG tol ~ 1/iter^(2.00)
eps = 1.00e-05, alpha = 1.50, max_iters = 5000, normalize = 1, scale = 1.00
acceleration_lookback = 10, rho_x = 1.00e-03
Variables n = 3, constraints m = 9
Cones:	linear vars: 9
Setup time: 7.70e-02s
SCS using variable warm-starting
----------------------------------------------------------------------------
 Iter | pri res | dua res | rel gap | pri obj | dua obj | kap/tau | time (s)
----------------------------------------------------------------------------
Failure:Interrupted
SUCCESSFULLY INSTALLED SCS
(If using SCS with CVX, note that SCS only supports CVX v3.0 or later).
```

**Comment by bodono** [comment]
I have no idea why this is happening, I have a mac and can run Matlab on it and I don't get this. I can try a fix that might work if I could send you a patch to apply and test it?

**Comment by hayata-yamasaki** [comment]
If you could try a fix and could send me a patch, I will gladly test it.

**Comment by bodono** [comment]
Ok, so try this:
```bash
cd scs-matlab/scs
git pull
git checkout ctrlc_matlab_fix
```
and then in matlab `make_scs` as usual. Does that fix it?

**Comment by hayata-yamasaki** [comment]
With that patch, the installation is successful as follows.
I greatly appreciate your fix.

```
>> make_scs
Building with 'Xcode with Clang'.
MEX completed successfully.
Building with 'Xcode with Clang'.
MEX completed successfully.
Building with 'Xcode with Clang'.
MEX completed successfully.
Example run:
----------------------------------------------------------------------------
	SCS v2.1.0 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
----------------------------------------------------------------------------
Lin-sys: sparse-indirect, nnz in A = 27, CG tol ~ 1/iter^(2.00)
eps = 1.00e-05, alpha = 1.50, max_iters = 5000, normalize = 1, scale = 1.00
acceleration_lookback = 10, rho_x = 1.00e-03
Variables n = 3, constraints m = 9
Cones:	linear vars: 9
Setup time: 3.83e-02s
----------------------------------------------------------------------------
 Iter | pri res | dua res | rel gap | pri obj | dua obj | kap/tau | time (s)
----------------------------------------------------------------------------
     0| 1.15e+19  1.52e+19  9.26e-01  2.47e+18  6.45e+19  3.36e+19  1.96e-02 
    33| 1.46e-11  2.77e-11  2.37e-12  1.90e+00  1.90e+00  2.13e-16  2.44e+00 
----------------------------------------------------------------------------
Status: Solved
Timing: Solve time: 2.44e+00s
	Lin-sys: avg # CG iterations: 2.12, avg solve time: 1.27e-06s
	Cones: avg projection time: 9.28e-08s
	Acceleration: avg step time: 7.04e-02s
----------------------------------------------------------------------------
Error metrics:
dist(s, K) = 1.1157e-16, dist(y, K*) = 0.0000e+00, s'y/|s||y| = -6.0746e-18
primal res: |Ax + s - b|_2 / (1 + |b|_2) = 1.4573e-11
dual res:   |A'y + c|_2 / (1 + |c|_2) = 2.7671e-11
rel gap:    |c'x + b'y| / (1 + |c'x| + |b'y|) = 2.3695e-12
----------------------------------------------------------------------------
c'x = 1.9049, -b'y = 1.9049
============================================================================
----------------------------------------------------------------------------
	SCS v2.1.0 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
----------------------------------------------------------------------------
Lin-sys: sparse-direct, nnz in A = 27
eps = 1.00e-05, alpha = 1.50, max_iters = 5000, normalize = 1, scale = 1.00
acceleration_lookback = 10, rho_x = 1.00e-03
Variables n = 3, constraints m = 9
Cones:	linear vars: 9
Setup time: 5.96e-02s
----------------------------------------------------------------------------
 Iter | pri res | dua res | rel gap | pri obj | dua obj | kap/tau | time (s)
----------------------------------------------------------------------------
     0| 1.14e+19  1.54e+19  9.36e-01  2.16e+18  6.52e+19  3.45e+19  6.85e-02 
    35| 3.76e-11  7.13e-11  2.77e-11  1.90e+00  1.90e+00  6.77e-17  8.69e-02 
----------------------------------------------------------------------------
Status: Solved
Timing: Solve time: 1.64e-01s
	Lin-sys: nnz in L factor: 45, avg solve time: 4.33e-07s
	Cones: avg projection time: 1.26e-07s
	Acceleration: avg step time: 6.81e-06s
----------------------------------------------------------------------------
Error metrics:
dist(s, K) = 7.7096e-17, dist(y, K*) = 0.0000e+00, s'y/|s||y| = -6.0946e-18
primal res: |Ax + s - b|_2 / (1 + |b|_2) = 3.7640e-11
dual res:   |A'y + c|_2 / (1 + |c|_2) = 7.1314e-11
rel gap:    |c'x + b'y| / (1 + |c'x| + |b'y|) = 2.7733e-11
----------------------------------------------------------------------------
c'x = 1.9049, -b'y = 1.9049
============================================================================
Warm-starting:
----------------------------------------------------------------------------
	SCS v2.1.0 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
----------------------------------------------------------------------------
Lin-sys: sparse-indirect, nnz in A = 27, CG tol ~ 1/iter^(2.00)
eps = 1.00e-05, alpha = 1.50, max_iters = 5000, normalize = 1, scale = 1.00
acceleration_lookback = 10, rho_x = 1.00e-03
Variables n = 3, constraints m = 9
Cones:	linear vars: 9
Setup time: 4.96e-02s
SCS using variable warm-starting
----------------------------------------------------------------------------
 Iter | pri res | dua res | rel gap | pri obj | dua obj | kap/tau | time (s)
----------------------------------------------------------------------------
     0| 4.41e-11  7.53e-11  3.04e-12  1.90e+00  1.90e+00  1.07e-16  2.87e-02 
----------------------------------------------------------------------------
Status: Solved
Timing: Solve time: 1.45e-01s
	Lin-sys: avg # CG iterations: 1.00, avg solve time: 7.38e-06s
	Cones: avg projection time: 1.40e-06s
	Acceleration: avg step time: 4.30e-08s
----------------------------------------------------------------------------
Error metrics:
dist(s, K) = 7.7096e-17, dist(y, K*) = 0.0000e+00, s'y/|s||y| = -6.1304e-18
primal res: |Ax + s - b|_2 / (1 + |b|_2) = 4.4104e-11
dual res:   |A'y + c|_2 / (1 + |c|_2) = 7.5251e-11
rel gap:    |c'x + b'y| / (1 + |c'x| + |b'y|) = 3.0363e-12
----------------------------------------------------------------------------
c'x = 1.9049, -b'y = 1.9049
============================================================================
SUCCESSFULLY INSTALLED SCS
(If using SCS with CVX, note that SCS only supports CVX v3.0 or later).
```

**Comment by bodono** [comment]
Great, thanks for testing, this is in master now.
