### ISSUE TITLE
SCS warning

### ISSUE THREAD

**Issue by dinesh286** [cvxgrp/scs#118]
I am using SCS in CVXPY for solving a mars landing problem.  I could get the optimal solution, but i getting a warning 
WARN: aa_init returned NULL, no acceleration applied.

what does it mean?

**Comment by kalmarek** [comment]
https://github.com/cvxgrp/scs/search?q=WARN%3A+aa_init+returned+NULL%2C+no+acceleration+applied&unscoped_q=WARN%3A+aa_init+returned+NULL%2C+no+acceleration+applied

also:
https://github.com/cvxgrp/scs/commit/d3d1d4c49b0aede0ec491fe06c99aef5cfe598c7

TLDR: you can ignore it

**Comment by bodono** [comment]
Yeah it's probably just because you've set the 'acceleration_lookback' parameter to 0. I should actually silence that warning, so I'll leave this open to remind me to do that.

**Comment by condnsdmatters** [comment]
I'm actually getting a similar error, when going through `cvxpy`, even when I set `acceleration_lookback` to be, say, 10 as a keywork argument to `Problem.solve`

**Comment by bodono** [comment]
If you're seeing `aa_init returned NULL` when you set that parameter it's most likely because SCS has been compiled without blas /lapack support, which is required for the acceleration step (and the projection onto the semidefinite cone, if you have any of those in your problem).

**Comment by condnsdmatters** [comment]
ah great, okay i'll have a check. just now i sent in the `verbose` keyword and the it looked as the the solver was ignoring my override of the `acceleration_lookback` setting it to `0` - i dont know if that chimes with what you'd expect in the above case. Either way will check out.

**Comment by bodono** [comment]
That confirms it then, since [here](https://github.com/cvxgrp/scs/blob/master/src/scs.c#L86) we have
```c
#ifdef USE_LAPACK
  scs_int acceleration_lookback = stgs->acceleration_lookback;
#else
  scs_int acceleration_lookback = 0;
#endif
```

**Comment by condnsdmatters** [comment]
hmm... so the binary that comes with pip version of `cvxpy` presumably is a wheel that isn't precompiled with lapack/blas?  I'll see if i can double check this, as it might also be the problem faced by @dinesh286

**Comment by sankethvedula** [comment]
Hi @bodono! I installed `scs` through pip and am getting this error message -- the reason is probably, like you mentioned, `lapack/blas` is configured properly. If I don't want to make use of this acceleration, is there any simple way that I can silence this warning?

**Comment by huynguyencse** [comment]
Hi! Is there any way to disable this warning when I execute the CVXPY program?

**Comment by bodono** [comment]
Just pushed a change to disable this warning if verbose = False.

**Comment by Hello-Toufu** [comment]
I 

> Just pushed a change to disable this warning if verbose = False.

Hi! I am facing the same issues, and the solution mentioned above, i.e., setting "verbose = False" can't disable this warning.

**Comment by bodono** [comment]
Should be fixed on PyPi now.

**Comment by erelsgl** [comment]
I still have this issue even when setting verbose=False. I have SCS 2.1.1.post2, and CVXPY 1.0.25, which pip3 says is uptodate.

**Comment by bodono** [comment]
If you upgrade to SCS 2.1.2 (the latest on pip) the warning should go away: https://pypi.org/project/scs/
