### ISSUE TITLE
python setup.py imports numpy while having it as a dependency

### ISSUE THREAD

**Issue by ido** [cvxgrp/scs#85]
In `scs/python/setup.py`, the `numpy` module is imported while also being an installation dependency.  This means that if the user is unlucky enough to come across `scs` in a dependency chain (e.g. when installing modules into a virtualenv with pip from a `requirements.txt` file), then the installation will fail because the module is imported in the `setup.py` script before pip has a chance to resolve the dependency and install `numpy` ahead of `scs`.  (One possible solution is to avoid using `numpy` in `setup.py` or at least to wrap the import statement in a try...except block and behave appropriately upon ImportError.)

To reproduce, in a fresh virtualenv of Python installation, `pip install cvxpy` in advance of `numpy` should trigger this behavior:  When installing the `scs` Python module via `pip`, the following error is encountered...
```
Collecting scs>=1.1.3 (from cvxpy->fancyimpute->-r requirements.txt (line 48))
  Downloading scs-1.2.7.tar.gz (280kB)
    100% |████████████████████████████████| 286kB 3.2MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_moyrnsq/scs/setup.py", line 4, in <module>
        from numpy import get_include
    ModuleNotFoundError: No module named 'numpy'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_moyrnsq/scs/
```

**Comment by bodono** [comment]
Thanks for flagging this, I can reproduce it. I think I can create a fix that's similar to the one in CVXcanon here https://github.com/cvxgrp/CVXcanon/pull/27.

I will try and submit something soon.

**Comment by tcchiao** [comment]
Hi there, 

I've just ran into this problem while using piptools to resolve dependencies: 
```2.0.2.tar.gz (133kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-t6k7dnl5/scs/setup.py", line 4, in <module>
        from numpy import get_include
    ModuleNotFoundError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-t6k7dnl5/scs/```. 

Wondering if the fix has been incorporated in a different release that I could try? Thanks a lot in advance for your help!

**Comment by bodono** [comment]
I haven't actually gotten around to fixing this yet, but if you pip install numpy and scipy first, then pip install scs it should work.

**Comment by tcchiao** [comment]
Gotcha, we were able to find a way to let piptools install numpy before scs. Thanks @bodono!

**Comment by bodono** [comment]
Fixed now in the scs-python repo (https://github.com/bodono/scs-python).

**Comment by zbluhm** [comment]
Hi, I am still getting this error:
```
Collecting scs==2.0.2 (from -r requirements.txt (line 10))
  Downloading https://files.pythonhosted.org/packages/b3/fd/6e01c4f4a69fcc6c3db130ba55572089e78e77ea8c0921a679f9da1ec04c/scs-2.0.2.tar.gz (133kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-a8o_98k4/scs/setup.py", line 4, in <module>
        from numpy import get_include
    ModuleNotFoundError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-a8o_98k4/scs
```

Here is what my requirements.txt looks like:
```
numpy==1.15.2
cvxpy==1.0.10
dill==0.2.8.2
ecos==2.0.7rc2
fastcache==1.0.2
future==0.16.0
multiprocess==0.70.6.1
osqp==0.4.1
scipy==1.1.0
scs==2.0.2
six==1.11.0
toolz==0.9.0
```

Please let me know if there are any other details I can provide, thanks!

**Comment by AtsushiSakai** [comment]
@bodono Hi. I am also getting this error :

    Collecting scs>=1.1.3 (from cvxpy->-r C:\projects\pythonrobotics\condaenv.0ojpv32y.requirements.txt (line 2))
    Downloading https://files.pythonhosted.org/packages/b3/fd/6e01c4f4a69fcc6c3db130ba55572089e78e77ea8c0921a679f9da1ec04c/scs-2.0.2.tar.gz (133kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\appveyor\AppData\Local\Temp\1\pip-install-rrg6j44o\scs\setup.py", line 4, in <module>
        from numpy import get_include
    ModuleNotFoundError: No module named 'numpy'

My environment.yml is:

    dependencies:
    - python==3.6
    - matplotlib
    - scipy
    - numpy
    - pandas
    - pip:
        - cvxpy

Best

**Comment by devang1994** [comment]
@bodono I still run into this error when installing cvxpy, which in turn relies on scs. 

Looking at the release history for the package on PyPI https://pypi.org/project/scs/#history , I noticed that your recent changes haven't yet made it to the main release. Is there any chance you could do a new PyPI release ?

**Comment by bodono** [comment]
Ok I'll cut a new release in the next few days.

**Comment by devang1994** [comment]
@bodono Sorry to bother you again, any chance you managed to have a look ?

**Comment by bodono** [comment]
It's up on pip for a few days now, does it not work for you?

**Comment by devang1994** [comment]
Hey @bodono I updated all our dependencies, works great now ! Thanks a lot for sorting this out
